<#
Code generated by Microsoft (R) PSSwagger 0.3.0
Changes may cause incorrect behavior and will be lost if the code is regenerated.
#>

<#
.SYNOPSIS
    

.DESCRIPTION
    

.PARAMETER MigrationMode
    

.PARAMETER Name
    The human readable name of the plan

.PARAMETER PolicyId
    

.PARAMETER Schedule
    {AvePoint.Migration.Api.Models.ScheduleModel}

#>
function New-FSPlanSettingsObject
{
    param(    
        [Parameter(Mandatory = $false)]
        [ValidateSet('HighSpeed', 'CSOM')]
        [string]
        $MigrationMode,
    
        [Parameter(Mandatory = $true)]
        [string]
        $Name,
    
        [Parameter(Mandatory = $false)]
        [string]
        $PolicyId,
    
        [Parameter(Mandatory = $false)]
        [Microsoft.PowerShell.AMPMigration.v001.Models.ScheduleModel]
        $Schedule
    )
    
    $Object = New-Object -TypeName Microsoft.PowerShell.AMPMigration.v001.Models.FSPlanSettingsModel

    $PSBoundParameters.GetEnumerator() | ForEach-Object { 
        if(Get-Member -InputObject $Object -Name $_.Key -MemberType Property)
        {
            $Object.$($_.Key) = $_.Value
        }
    }

    if(Get-Member -InputObject $Object -Name Validate -MemberType Method)
    {
        $Object.Validate()
    }

    return $Object
}
